### ISSUE TITLE
Alignment Strings

### ISSUE THREAD

**Issue by fbemm** [lh3/minimap2#9]
Dear Heng,

would it be possible to optionally output the reference and query alignment string (potentially without hard and soft clipped sequences) in the PAF format?

Thanks,
Felix

**Comment by lh3** [comment]
I have been thinking to encode sequences and alignment with one string. For example, the following alignment:
```
ref: CGATCGATCACT--TAAC
     || |   ||  |  ||||
qry: CGTT---TCGGTAATAAC
```
is encoded as `=CG*AT-CGA=TC*AG*CG=T+AA=TAAC`. Here `=` represents a block of identical sequences, while `*`, `-` and `+` represents a single substitution, a block of deletions and a block of insertions, respectively. The goal is to concisely encode two sequences and CIGAR in one string. If this works for you, I can make it happen at some point.

**Comment by fbemm** [comment]
Looks good! Should be straight forward to convert that into MAF format then (which some tools surprisingly still use).

**Comment by lh3** [comment]
Ok, good. I will get it done in a few days.

**Comment by lh3** [comment]
I kind of like the idea, so implemented earlier. Please see the [cs-tag](https://github.com/lh3/minimap2/tree/cs-tag) branch. The string encoding both sequences and cigar will be written to a `cs` tag if you align with:
```sh
./minimap2 -cS test/MT-human.fa test/MT-orang.fa > out.paf
```
Let me know how it works. If it is fine, I will merge the change to the master branch at some point.

**Comment by fbemm** [comment]
Format works great but it sort of troubles me ;) I uploaded an example (https://drive.google.com/open?id=0BwX5gnQzGAU8aWFjRFREakpLOW8). Alignment block should be ~600kb but the cs field operations create alignment sequences with a size of ~3Mb. Likely that I am doing something wrong here ;)

**Comment by lh3** [comment]
Sorry. That was due to a bug. I have fixed that one. Let me know if you find more. Thanks!

**Comment by fbemm** [comment]
Thanks! We are almost there :) 

A similar one still appears here. CIGAR says 1232M but the CS field operations end up with 1312 and cause an overhang.

"Chr2    19682547        19681292        19682524        +       Chr4    18585056        3950524 3951756 1153    1232    0       tp:A:P  cm:i:7  s1:i:106        s2:i:125        NM:i:72 ms:i:505        AS:i:505        nn:i:7  cg:Z:1232M      cs:Z:=TATGAGTCTTTGGCTTTGT*ga=TCTTCTAACAAGGA*ta=ACACTACTTAGGCTT*ta=TAAGATCG*ag=GT*ta=GCGGTTTAAGTT*gc=TT*ta=TACTCAATCATA*ca=ACATGACA*at=CAAGTCATATTCGACTCCAAAACACTAACCAACCT*ta=CTTCTTGCTTCTCAAAGCTTTCA*ct=GGTGTAGCCAAAGTCCATATGAGTCTTTGGCTTTGTGTCTTCTAACAAGGA*ta=ACA*gc=T*ta=CTTA*cg=GC*ct=T*ta=TAAGATC*cg=GGTTGC*ag=GTTTAAGTT*gc=TTA*ta=ACTCAATCATACACATGACATCAAGTCATA*ct=T*ct=GACTCCAAAACACTAACCAACCTT*gc=TTCT*ta=GCTTCTCAAAGCTTTCATGGTGTAGCCAAAGTCCATATGAGTCTTTGGCTTTGT*ga=TCTTCTAACAAGGAAACACTACTTAGGCTT*ta=TAAGATCG*ga=GTTGCGGTTTAAGTT*gc=TTATA*cn=TCAATCATACACATG*ta=CATCAAGTCATATT*tc=GACTCCAAAACACTAACCAACCT*ta=CTTCTTGCTTCTCAAAGCTTTCATGGT*tg=TAGCC*ta=AAGTCCATATGAGTCTTTGGCTTTGTGTCTTCTAACAAGGA*ta=ACA*gc=T*ta=C*at=TA*cg=GC*ct=T*ta=TAAGATC*cg*ag=GTTGCGGTTTAAGTT*gc=TTATACTCAATCATA*ac=ACATGACATCAAGTCATATT*ct=GACTCCAAAACACTAAC*ac=AACCTTCTTCTAGCTTCTCAAAGCTTTCATGGTGTAGCCAAAGTC*gc*ga=TATGA*tg=TCTTTGGCTTTGTAT*gc=TTCTAACAAGGAAACACTACTTAGGCTTATAAGATCGG*ag=TTGCGGTTTAAGTT*gc=TTATACTCAATCATACACATGACATCAAGTCATATTCGACTCCAAAACACTAACCAACCTTCTT*tc=T*at=GCTTCTCAAAG*tc=TTTCATGGTGTAGCCAAAGT*cg=C*ga=TATGAGTCTTTGGCTTTGT*at=T*gc=TT*tc=TAACAAGGAAA*cg=ACTACTTAGGCTTATAAGATC*cg=GGTT*gn*tc=GGTTTAAGTTCTTATACTCAATCATACACATGACATCAA*gn=TCA*tc=ATTCG*an=CT*cn=C*an=AAACACTAACCAACCTTC*at=TCTTGCTTCTCAAAGCTTTCATGGTTTAGCCTAAGTCCATATGAGT*cg*gt=TTGGCTTTGTGTCTTCTAACAAGGAAACTCTACTTAG*cg=CTTTTAAGATCGGGTTGCGGTTTAAGTT*gn=TTATACTCAATCATACACATGACATCAAGTCATATTCGACTCCAAAAC*ta=CTAACCAACC*ct=TCTTCT*at=GCTTCTCAAAGCTTTCATGGT"

**Comment by lh3** [comment]
This one is correct. The following gives the query sequence in the alignment (because there are no gaps):
```sh
perl -ne 'print "$1\n" if /cs:Z:(\S+)/' in.paf|perl -pe 's/\*[a-z]([a-z])/$1/g;s/=//g'|wc
```
The output is `1233`, which is correct (including the trailing `\n`).

**Comment by lh3** [comment]
This is probably due to different understanding of the new `cs` encoding. Note that `*ct` encodes a mismatch, where the `c` base comes from the reference and `t` from the query.

**Comment by fbemm** [comment]
Totally correct. Everything looks good now. Spotted one weird alignment but that is not related to the cs encoding.

"CTG_036 31003   9815    11611   -       Chr3    23459830        17393357        17395049        1595    1830    27      tp:A:P  cm:i:71 s1:i:906        s2:i:939        NM:i:235        ms:i:672        AS:i:641        nn:i:0  cg:Z:942M73I134M33D49M32I70M31I82M1I239M1D113M1I29M     cs:Z:*at*cg*gc*gc*ta*cg*at*at*ta*ta*cg*cg*cg*ta*at*at*cg*gc*ta=G*ta*at*cg*cg*ta*ta*at*at*cg*ta*at*at*ta*at*at*gc*ta*ta*at*gc*at*ta*cg*gc*ta*ta*at*cg*at*ta*at*cg*cg*ta*ta*gc*gc*cg*cg*at*at*ta*at*ta*gc*cg*gc*gc*at*ta*ta*ta*gc*at*cg*ta*cg*cg*ta*ta*at*gc*cg*cg*cg*at*ta*ta*ta*gc*ta*cg*gc*cg*cg*ta*ta*at*ta*ta*cg*cg*at*ta*ta*ta*gc*ta*ta*tg*at*at*cg*gc*at*ta*ta*cg*ta*ac*at*ta*cg*cg*gc*at*ta*cg*gc*ta*gc*ta*at*ta*ta*gc*at*ta*gc*gt*at*cg*cg*at*at*ta*cg*ta*ac*ta*at*ta*cg*gc*ta*ta*at*cg*ta*ta*at*gc*cg*cg*at*ta*at*tg*at*at*cg*cg*at*at*cg*cg*at*at*cg*cg*cg*cg*at*cg*ta*gc*ac*ta*cg*ta*at*at=G*ta*at*cg*at*at*cg*gc*at*ta*at*gc*at*gc*at*ta*ta*gc*gc*gc*gc*at*ta*cg*gc*ta*at*cg*gc*at*ta*ta*cg*cg*cg*ta=T*gc*ta*ta*ta*cg*at*cg*gc*at*ta*gc*gc*cg*cg*gc*at*at*ta*ta*at*at*ac*cg*ta*at*ta*ta*gc*gc*cg*ta*cg*at*ta*ta*gc*gc*ta*cg*cg*at*ta*cg*cg*gc*ta*ta*cg*ta*cg*cg*at*gc*at*cg*gc*ta*at*cg*gc*ta*cg*cg*cg*ta*cg*cg*gc*gc*cg*ta*at*cg*at*ta*gc*gc*ta*gt*at*at*cg*gc*at*ta*ta*gc*at*gc*cg=G*cg*ta*cg*gc*gc*cg*ta*ta*at*ta*cg*gc*at*at*cg*ta*at*ta*cg*cg*at*ta*gc*ta*ta*ta*cg*cg*gc*at*ta*cg*cg*gc*gc*ta*cg*gc*ta*ta*ta*at*at*cg*at*cg*ta*at*cg*gc*at*cg*cg*gc*cg*cg*cg*at*cg*gc*gc*ta*ta*ta*at*cg*ta*at*at*cg*cg*gc*ta*ta*ta*at*cg*cg*cg*gc*ta*cg*cg*gc*gc*ta*cg*cg*at*ta*gc*gt*ta*gc*gc*ta*cg*gc*at*ta*at*at*at*gc*cg*ta*ta*ta*cg*gc*gc*cg*ta*ta*at*at*ta*gc*at*ta*cg*cg*at*ta*cg*cg*at*ta*gc*cg*gc*gc*ta*cg*cg*gc*at*at*cg*gc*at*ta*at*ta*cg*cg*ta*ta*at*ta*cg*at*cg*at*cg*cg*cg*at*at*gc*gc*gc*ta*cg*cg*gc*ta*gc*gc*at*ta*ta*cg*at*ta*cg*cg*at*tg*cg*gc*gt*at*ta*cg*at*ta*cg*gc*ta*at*gc*gc*cg*ta*at*gc*cg*cg*cg*at*ta*gc*at*at*at*ta*cg*cg*ta*ta*cg*cg*ta*cg*cg*gc*ta*cg*gc*gc*cg=G*ta*ta*at*gc*gc*ta*ta*ta*gc*cg*ta*cg*at*cg*gc*gc*gc*ta*cg*cg*at*at*cg*at*ta*cg*cg*gc*ta*ta*ta*ta*gc*tg*cg*cg*at*ta*cg*gc*gc*ta*ta*cg*cg*cg*at*cg*cg*gc*ta*gc*gc*at*cg*ta*ta*ta*cg*cg*cg*gc*ta*ta*gc*gc*ta*ta*at*ta*cg*cg*gc*ta*cg*gc*at*gc*ta*cg*at*cg*cg*cg*ta*ta*ta*gc*gc*ta*cg*ta*ta*at*cg*cg*gc*at*ta*cg*ta*cg*cg*gc*at*ta*cg*gc*gc*ta*ta*ta*cg*at*cg*cg*at*ta*gc*gc*cg*ta*ac*at*gc*gc*at*gc*at*ta*at*gc*at*ta*at*cg*at*ta*gc*at*at*gc*gc*cg*at*gc*cg*cg*gc*cg*gc*at*ta*at*ta*ta*gc*at*ta*cg*cg*ca*at*ta*at*ta*gc*gc*ta*gc*at*at*ta*cg*at*cg*gc*ta*ta*cg*cg*ta*ta*at*cg*cg*cg*at*ta*ta*cg*ta*ta*gc*gc*ta*gc*cg*ta*ta*ta*cg*ta*cg*cg*cg*ta*ta*ta*at*cg*cg*gc*gc*ta*at*at*gc*at*ta*ta*gc*cg*at*ta*cg*cg*at*ta*gc*gc*gc*cg*gc*at*cg*cg*cg*ta*ta*gc*gc*gc*ta*gc*ta*gc*ta*cg*cg*gc=G*at*ta*gc*cg*at*cg*ta*ta*at*ta*cg*cg*ta*ta*gc*ta*gc*cg*ta*ta*cg*cg*ta*cg*gt*at*at*cg*at*cg*ta*ta*ta*ta*cg*ta*cg*gc*at*ta*cg*cg*at*ta*cg*cg*cg*at*ta*cg*cg*gc*at*cg*gc*at*ta*cg*ac*gc*ta*cg*ta*ac*ta*ca*ta*gc*at*cg*cg*cg*ta*ta*cg*cg*gc*ta*cg*ta*gc*at*cg*gc*at*ta*cg*gc*gc*cg*cg*ta*gt*ta*cg*cg*cg*at*ta*cg*cg*gc*at*ta*cg*ca*gc*ta*cg*cg*gc*at*cg*gc*at*ta*ta*gc*gc*ta*cg*ta*gc*ta*gc*cg*gt*at*ta*cg*cg*at*at*ta*cg*cg*gc*ta*cg*ta*gc*gc*cg*cg*gc*at*ta+ggctaggcaggctgttaaccagacacgctaggttaggcagaccggctaggctagacaggctgctagccagacc*cg*cg*gc*at*ta*cg*cg*gc*at*ta*cg*cg*gc*at*cg*gc*at*ta*cg*gc*gc*ta*cg*ta*at*cg*cg*ac*gc*at*ta*cg*tg*gc*at*ta*ta*cg*gc*ta*cg*ta*cg*ta*at*ag*gc*at*cg*gc*at*at*cg*gc*gc*ta*cg*ta*at*cg*cg*cg*ta*cg*ta*cg*cg*at*ta*cg*cg*ta*cg*ta*at*cg*at*cg*ta*cg*cg*at*ta*cg*gc*at*at*cg*cg*gc*ta*ta*gc*gc*at*cg*cg*gc*gc*gc*at*gc*gc*ta*at*gc*ta*at*ta*gc*cg*gc*cg*at*ta*cg*at*gc*ta*ta*cg*gc*gc*ta*cg*gc*at*gc*ta*ta*at*ta*at*cg-tcgccgagccgcacccctttccgaccaacaact*ta*cg*at*gc*gc*at*ta*gc*ta*gc*ta*ta*gc*gc*gc*at*cg*ta*cg*ta*ta*ta*ta*at*at*gc*at*at*ta*gc*ta*ta*ta*ta*gc*ta*gc*gc*ta*gc*ta*ta*ta*ta*gc*at*at*ta*gc+aacactctactacactctactaacactctact*ta*ta*gc*ta*gc*at*gc*at*ta*gc*at*ta*ta*cg*cg*at*at*at*gc*gc*cg*cg*ta*ta*gc*gt*gt*cg*gc*ta*cg*cg*ta*cg*cg*cg*ta*ta*at*ta*at*ta*at*gc*gc*gc*gc*gc*cg*gc*at*at*ta*gc*gc*at*ta*gc*cg*ta*ta*cg*cg*cg*gc*at*at*gc*cg*at+agtgtaggcaaggaacgtgggaaggctttcc*ta*cg*at*cg*at*ta*cg*cg=C*ta*ta*cg*cg*ta*ga*gc*cg*at*tg*cg*cg*ta*ta*cg*cg*gc*at*at*at*gc*gc*ta*cg*at*cg*at*ta*cg*cg*gc*ta*ta*cg*cg*ta*ta*gc*cg*at*ta*ca*cg*ta*ta*cg*cg*gt*at*ac*at*gc*gc*ta*cg*at*cg*at*ta*cg*cg*gc*ta*ta*cg*tg*ta*ta*gc*tg*at*ta*cg+a*ct*ta*ta*tc*gc*gc*ta*gc*at*ta*gc*cg*at*at*cg*ta*gc*ta*ta*ca*gc*ta*ta*gc*gc*ta*at*cg*cg*cg*gc*cg*ta*cg*gc*at*cg*cg*ta*ta*at*cg*at*cg*cg*ta*ta*ta*ta*gc*gc*ca*cg*gc*at*gc*at*cg*at*cg*cg*ta*cg*ta*ta*cg*at*cg*cg*ct*gc*ta*gc*at*gc*cg*ta*at*cg*cg*at*cg*at*gc*ta*cg*at*at*cg*tg*at*gc*cg*ta*cg*gc*at*gc*ta*gc*ta*cg*at*gc*ag*ta*gc*at*cg*ca*gc*gc*at*cg*cg*at*cg*cg*cg*at*ac*cg*ta*gc*gc*gc*ta*cg*at*gc*ta*at*cg=T*cg*gc*at*ta*cg*at*gc*cg*ta*cg*at*cg*cg*gc*at*gc*cg*ta*cg*at*gc*ta*cg*gc*at*gc*cg*ta*gc*ta*tg*gc*gc*ta*cg*at*gc*cg*ta*cg*at*cg*cg*ta*at*gc*cg*ta*gt*at*gc*cg*ta*at*gc*cg*ta*at*gc*ta*cg*ta*ta*cg*cg*at*tc*cg*ta*gc*gc*ta*ta*ta*at*gc*cg*ta*cg*at*cg*cg*ta*at*gc*cg*ta*ta*at*gc*cg*ta*at*gc*cg*ta*at*gc*ta*ta*cg*at*ta*cg*cg-t*at*gc*tg*ta*ta*gc*ta*cg*cg*at*gc*cg*ta*cg*at*cg*cg*ta*at*gc*cg*ta*gc*gc*ta*ta*cg*at*gc*cg*ta*ta*gc*at*at*cg*ta*ta*ta*cg*ta*cg*gc*ta*ta*cg*ta*ta*cg*cg*gc*at*cg*ta*at*at*gc*ta*at*ta*ta*ta*ta*ac*gc*ta*cg*cg*ac*ta*ta*tg*ct*ta*tg*gc*at*cg*cg*at*ta*gc*gt*ta*cg*ta*at*gc*ta*ta*ta*ta*tg*ta*cg*cg*ta*at*at*at*at*cg*at*at*ct*cg*tg*gc*gc*cg*cg*ta*cg+a*ta*ta*ta*at*ta*gc*at*at*cg*gc*cg*gc*gc*gc*at*cg*gc*cg*gc*gc*ta*cg*gc*ta*ta*at*cg*at*at"

**Comment by lh3** [comment]
Minimap2 must be doing something silly with your example. NM says 235, but there are clearly more mismatches than 235. I am sorry for these bugs. I will debug the cs string more throughly after getting a few things sorted at hand. I will keep this issue open until I really fix it.

**Comment by lh3** [comment]
I have pushed a quick fix for the bug you saw. As I said, I will test the new feature more thoroughly later. I will probably add a few minor features along the way. Thank you for testing immature features and sorry for the hassle.

**Comment by lh3** [comment]
I believe I have fixed all the issues in the `cs` tag. You can find the latest version at the [dev branch](https://github.com/lh3/minimap2/tree/dev).

I have added a new script to print BLAST-like output and to convert to MAF. To use it:
```sh
wget -O- https://github.com/attractivechaos/k8/releases/download/v0.2.3/k8-0.2.3.tar.bz2|tar -jxf - k8-linux
./k8-linux misc/paf2aln.js with-cs.paf | less -S # BLAST-like
./k8-linux misc/paf2aln.js -m with-cs.paf > aln.maf
```

I will close this issue. If you still find `cs` is buggy, please reopen it. If the conversion script has issues, you may open a new one. Thanks a lot for the feature request and helping me to fix the bugs in it.

**Comment by fbemm** [comment]
paf2aln works charming. Thanks for that! Concerning asm-vs-asm it would makes sense to optionally in-cooperate also unaligned sequence chunks so that one can rebuild the two input asm's completely from the paf/maf files (but that might be a special usage scenario like http://fenderglass.github.io/Ragout).
